### ISSUE TITLE
User defined hinting macros 

### ISSUE THREAD

**Issue by soubiliz** [jun7/wyeb#26]
It would be nice to have the possibilities to use call a script with hinting.
For example in luakit I defined a script to call mpv when the hinted url is a video.
I suggest to map macro with `,` plus a key

**Comment by jun7** [comment]
Make a sh file like below (if mpv works with URI) to the menu dir
.hintmpv
```wyeb // shhint 'mpv $MEDIA_IMAGE_LINK'```
then edit the accels in the conf dir to assign a key.
(if wyeb is running, the line of the sh is automatically added)

not works?

**Comment by soubiliz** [comment]
Okay I don't understand how `accels` do works I tried this by refering to the doc `(gtk_accel_path "<window>/.hintmpv" "<Primary><Shift>z")`
with no success but without the `.` I was able to use it with the menu

**Comment by jun7** [comment]
The first chars of file names are for display order or hidden flag. It is ignored by wyeb.

Anyway, thank you for reporting.

**Comment by soubiliz** [comment]
the issue wasn't that but how the doc is written about accels.
There is two different docs and there both wrong.
Inside the README.md you say that for Ctrl-z you have to but "z" and in the integrated one the it's `<Primary><Shift>z`
but to map Ctrl-Z it's `<Primary>z`

**Comment by jun7** [comment]
It means Z is not works on the accels but have to add `<Shift>`

On the README.md `<xxx>` are removed because of it is markdown.
I will fix it thank you.
