### ISSUE TITLE
Link hints not showing up on heavy pages with opengl rendering

### ISSUE THREAD

**Issue by sdsddsd1** [jun7/wyeb#37]
Hello,
wyeb´s link hints crashes when webkit2gtk is compiled with opengl and wpe-renderer.
The hints are working on pages without javascript but when I visit a fancy site they dont apear anymore, although they remain functional. When I vist a simple page again, they dont show up until I restart wyeb. Webkit2gtk version: 2.28.2.
Webkit2gtk compiled without opengl works just fine.

**Comment by jun7** [comment]
Progress bar is drawn? (It uses same event and canvas)
URI entry is drawn? (Other widgets on the web view are working?)
Do the hints work without drawn? (only visibility?)
Does the adblock work? (Other extensions are working?)
Key "a" shows blocked resources? (Is the extension containing the hints working?)

**Comment by jun7** [comment]
Ah is it default option?

**Comment by sdsddsd1** [comment]
fancy=javascript and bling bling | simple=plain text 
- Progressbar: not working on fancy sites. It shows up super short on startup(bookmark). I cant tell on simple sites because its loading too fast.
- Uri entry=url bar? This is working on all sites
- Hints are working when not drawn
- I only have adblock and this seems to work. No ads, process is running. Windowswitcher is never working.
- Key "a": shows blocked domains and only https . No hints in there.
All tested with default config.

**Comment by jun7** [comment]
> I cant tell on simple sites because its loading too fast

Pointer Mode's "+" is drawn? (Pointer mode is assigned key 'p')
It is also same as hints.

**Comment by sdsddsd1** [comment]
It enters pointer mode, but no red dot is drawn.

**Comment by jun7** [comment]
Is it fixed?

**Comment by sdsddsd1** [comment]
No.
Now the linkhints also dont show up on simple sites. Rest of the testings like above.

**Comment by jun7** [comment]
I updated the commit. Is it fixed.

**Comment by sdsddsd1** [comment]
Yibbie!
Link hints are working now. Thanks for fixing this!  
Windowswitcher widget now also pops on.
One thing left is that the thumbnails from the history are not shown.  
This is a minor thing and not important for me but I want to mention.
[screenshot](https://ibb.co/jwvPzR2)

**Comment by jun7** [comment]
Is the Windowswitcher key 'z' ?
Is it normal? It uses same function as the history images.

**Comment by sdsddsd1** [comment]
Yes this does the same "image".

**Comment by jun7** [comment]
The commit kills drag and drop. So I will revert the commit and take another way.

**Comment by sdsddsd1** [comment]
The last commit removed the link hints and status bar again. Images still corrupted.

**Comment by jun7** [comment]
Hmm not reproduced.
What is your build options of webkit2gtk?
What is the fancy site?

**Comment by sdsddsd1** [comment]
After your last commit the link hints are gone on every website. Also no progress bar or widgets coming up. 
The commit before worked (link hints, widget). Minus the corrupted thumbnails.
As fancy site I tested [spiegel.de](www.spiegel.de) . But the behaviour was on every page. (Github, Youtube)
We have not talked about this, but its also on sway + wayland.  
But sway + webkit2gtk (opengl off and wpe off) worked fine with hints and widgets.

Webkit2gtk: basically `opengl` and `wpe-renderer` on 
```
cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIB_INSTALL_DIR=/usr/lib \
    -DPORT=GTK \
    -DCMAKE_SKIP_RPATH=ON \
    -DENABLE_BUBBLEWRAP_SANDBOX=OFF \
    -DENABLE_SAMPLING_PROFILER=OFF \
    -DENABLE_GEOLOCATION=OFF \
    -DENABLE_GLES2=ON \
    -DENABLE_INTL=OFF \
    -DENABLE_INTROSPECTION=OFF \
    -DENABLE_MINIBROWSER=OFF \
    -DENABLE_OPENGL=ON \
    -DENABLE_SPELLCHECK=OFF \
    -DENABLE_VIDEO=${streaming:-OFF} \
    -DENABLE_WEBGL=OFF \
    -DENABLE_WEB_AUDIO=${streaming:-OFF} \
    -DUSE_LIBHYPHEN=OFF \
    -DUSE_LIBNOTIFY=OFF \
    -DUSE_LIBSECRET=OFF \
    -DUSE_OPENJPEG=${jpeg:-OFF} \
    -DUSE_WOFF2=OFF \
    -DUSE_WPE_RENDERER=ON \
    -DENABLE_WEB_CRYPTO=OFF \
    -DENABLE_MEDIASOURCE=${streaming:-OFF} \
    -Wno-dev
```

**Comment by sdsddsd1** [comment]
Note: Commit 069fb18 is working working for me with hints and widgets. No images.  
Latest commit does not work.  
Did you try to reproduce with webkit2gtk with opengl and fpe-renderer?
If you are not planing on more investigation we could close the issue.  
Thanks for your efforts anyway.
Greetings.

**Comment by jun7** [comment]
It is reproduced and will take a while to fix it.
Or I will set `hardware-acceleration-policy=NEVER` programmatically.

**Comment by jun7** [comment]
The fix works with weston. Is it fixed?

**Comment by sdsddsd1** [comment]
Link hints and widget (uribar) are working.
Channel switcher and history still have the corrupted image.
Tested on sway and hikari.

**Comment by sdsddsd1** [comment]
Last commit did it. Link hints and correct images!

**Comment by jun7** [comment]
BTW reordering windows (e.g. Channel switcher) not works on weston.
Does it work on sway?

**Comment by sdsddsd1** [comment]
When you mean keybind "z", it shows the window(picture) but does not switch to it.
This would be a nice feature because currently there is nothing like "tabbed" available. 
I use the tabbed mode of sway for it.
Edit:
I does not matter if its in tabbed, tiling or floating mode.

**Comment by jun7** [comment]
Hmm there is no left I can handle because I just use gtk_window_raise for reordering windows and gdk's one also not works too, so Thank you for reporting!
