### ISSUE TITLE
Caps lock binded to escape don't function as escape

### ISSUE THREAD

**Issue by heyitscassio** [jun7/wyeb#42]
I have my esc key binded to escape, but in wyeb it doesn't work.

**Comment by jun7** [comment]
I tested it as below and  key->is_modifier was true.
```
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
```

How do you bind it?

**Comment by jun7** [comment]
Ah I had missed reset mod.
Reset modmap and `xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'` works on wyeb.

**Comment by heyitscassio** [comment]
I use setxkbmap to to this, with this command:
`setxkbmap -model thinkpad60 -layout br -option caps:escape_shifted_capslock`

**Comment by jun7** [comment]
Hmm it makes is_modifier == true.

**Comment by heyitscassio** [comment]
Using `xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'` it works as intended, but it should work without it, right? Every other program works without xmodmap.

**Comment by jun7** [comment]
I've found `setxkbmap -option caps:escape` works.
So I'm stuck with what to support such a nonsense key event. ESC is not modifier.

**Comment by heyitscassio** [comment]
Yup, it works. Maybe it's not needed to support this obscure option, either way i never use it.
