### ISSUE TITLE
Open hint link in a external script

### ISSUE THREAD

**Issue by heyitscassio** [jun7/wyeb#43]
In vimb, qutebrowser or luakit i can set a keybind to enter hint mode, select a url, and this url is piped into mpv, so i can watch youtube videos on mpv. It's possible to do that with wyeb?

**Comment by jun7** [comment]
It is 'shhint'. (`wyeb // shhint 'mpv $LINK'`)
And see 'context-menu:' and 'accels:' section in help page.

**Comment by heyitscassio** [comment]
wyeb created a directory in `~/.config/wyeb.`, is this the default?

**Comment by jun7** [comment]
Yes. I didn't get a point of your question though.

**Comment by heyitscassio** [comment]
Why the trailing dot? there is some reason to that?

**Comment by jun7** [comment]
It is a separator for the Suffix. It hasn't to be a dot, even not necessary though.
When you use X to the suffix, the dir names are `wyeb.X`.

**Comment by heyitscassio** [comment]
got it, thanks!
