### ISSUE TITLE
possible support for xembed

### ISSUE THREAD

**Issue by Foxbud** [jun7/wyeb#7]
This is more of a question than anything. I've done a little bit of experimentation, but haven't figured anything out yet. Is wyeb xembed aware such that it could be used by tabbed window wrappers like 'tabbed' (if so, how)?

I have almost no understanding of how xembed works on a low level, but if wyeb doesn't support it, and you have some understanding of xembed, do you think it would be a useful addition to the browser?

**Comment by jun7** [comment]
Hi, I tested tabbed and got awful result because wyeb controls windows e.g. harf of btn actions are for it, also depends on it.

**Comment by jun7** [comment]
not works but for someone having interest or just a memo

	E+#include <gtk/gtkx.h>
	+static long plugto = 0;
	+
	 #include "general.c"
	 
	 #define MIMEOPEN "mimeopen -n %s"
	@@ -2299,6 +2302,8 @@ static bool _run(Win *win, gchar* action, const gchar *arg, gchar *cdir, gchar *
			gchar **retv = NULL; //hintret
	 
	 #define Z(str, func) if (!strcmp(action, str)) {func; goto out;}
	+       //experimental
	+       Z("plugto"     , plugto = atol(arg); return run(win, "new", arg))
			//nokey nowin
			Z("new"         , win = newwin(arg, NULL, NULL, false))
	 
	@@ -4094,7 +4099,8 @@ Win *newwin(const gchar *uri, Win *cbwin, Win *caller, bool back)
			Win *win = g_new0(Win, 1);
			win->userreq = true;
	 
	-       win->winw = gtk_window_new(GTK_WINDOW_TOPLEVEL);
	+       win->winw = plugto ?
	+               gtk_plug_new(plugto) : gtk_window_new(GTK_WINDOW_TOPLEVEL);
	 
			gint w, h;
			if (caller)

**Comment by jun7** [comment]
@Foxbud Hi I added tabbed support to wyeb. Now it works.
